name: Test
run-name: ${{ github.actor }}
#on:
#  workflow_run:
#    workflows: [Build Test]
#    branches: [main, test-branch]
#    types:
#      - completed

on:
  push:
    branches:
      - 'main'
      - 'test-branch'
jobs:
  Round-1:
    runs-on: ubuntu-latest
    environment:
      name: TestEnv
    env:
      Day: Monday
    steps:
      - run: echo ${{ secrets.MY_SECRET }}
      - run: echo ${{ vars.MY_VARIABLE }}
      - run: echo "$Day is the best day of the week!"
      - name: Set environment variables
        env:
          ENV_VAR: "default_value"
        if: github.ref == 'refs/heads/main'
      - name: Set environment variables
        env:
          ENV_VAR: "branch_value"
        if: startsWith(github.ref, 'refs/heads/feature/')

      - run: echo "$ENV_VAR"


#  Round-2:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: test-${{ github.sha }}
#          path: test
#
#      - run: cat test/test.txt
#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event. AND IT WORKED!"