name: TEST Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
      - 'test-branch'

jobs:
  Round-1:
    runs-on: ubuntu-latest
    needs: [ Round-2 ]
    environment:
      name: TestEnv
    env:
      Day: Monday
    steps:
      - run: echo ${{ secrets.MY_SECRET }}
      - run: echo ${{ vars.MY_VARIABLE }}
      - run: echo "$Day is the best day of the week!"

  Round-2:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: test
          path: test

      - run: cat test/test.txt
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event. AND IT WORKED!"